import { Component, Host, h, Prop, Element, Event, EventEmitter, Watch, Listen, State, Method } from '@stencil/core';
import { capitalize, isDateObject } from '../../utils/utils';
import arrowSvg from '../../assets/svg/arrow-triangle-down.svg';
import { IMxMenuItemProps } from '../mx-menu-item/mx-menu-item';
import { PaginationChangeEventDetail } from '../mx-pagination/mx-pagination';

export interface ITableRowAction extends IMxMenuItemProps {
  /* The menu item text for the row action */
  value: string;
}

/** Defines a data table column */
export interface ITableColumn {
  /** The property on each row object that will supply the column's cell values (as HTML).
   * You may also supply a `getValue` function for the value.  If both are provided,
   * the `property` will only be used for sorting.
   */
  property?: string;
  /** The displayed column heading */
  heading?: string;
  /** The value type, which may affect sorting and how the value is displayed
   * @default 'string'
   */
  type?: 'string' | 'number' | 'date' | 'dateTime' | 'boolean';
  align?: 'left' | 'center' | 'right';
  /** Whether the column may be sorted by clicking the header.  The column must specify a `property`
   * to be sortable.
   * @default true
   */
  sortable?: boolean;
  /** A getter function for the column cells' inner HTML.
   *
   * Note that a `property` is required to make a column with a value getter sortable.  If sorting
   * client-side, the property does not necessarily have to exist on the row objects; it is simply a
   * unique identifier for the table's `sortBy` prop.
   */
  getValue?: (row: Object, rowIndex?: number) => any;
  /** A custom compare function for sorting by this column (if sorting client-side) */
  sortCompare?: (rowA: Object, rowB: Object) => number;
  /** Additional classes to add to the header cell for this column */
  headerClass?: string;
  /** Additional classes to add to the body cells in this column */
  cellClass?: string;
}

@Component({
  tag: 'mx-table',
  shadow: false,
})
export class MxTable {
  actionMenu: HTMLMxMenuElement;
  actionMenuButton: HTMLMxButtonElement;
  hasSlot: boolean = false;

  /** An array of objects that defines the table's dataset. */
  @Prop() rows: Object[] = [];
  /** An array of column definitions.  If not specified, a column will be generated for each property on the row object. */
  @Prop() columns: ITableColumn[] = [];
  /** The name of the property on the row object to use as the `rowId` prop for each generated `mx-table-row`.
   * This is only required if the table is `checkable` and completely generated by the data. */
  @Prop() rowIdProperty: string;
  /** Additional classes for the `table` element */
  @Prop() tableClass: string;
  /** Make rows checkable.  You must either provide a `rowIdProperty` (for generated rows), or
   * provide a `rowId` for every `mx-table-row` if creating the rows manually in the table's slot. */
  @Prop() checkable: boolean = false;
  /** Set to false to prevent checking rows by clicking on them (outside the checkboxes). */
  @Prop() checkOnRowClick: boolean = true;
  @Prop() hoverable: boolean = true;
  /** Set to `true` to allow smaller tables to shrink to less than 100% width */
  @Prop() autoWidth: boolean = false;
  /** The property on the row objects that will be used for sorting */
  @Prop({ mutable: true }) sortBy: string;
  @Prop({ mutable: true }) sortAscending: boolean = true;
  /** Set to `true` to render the table in a loading state */
  @Prop() isLoading: boolean = false; // TODO: needed?
  /** Show the pagination component.  Setting this to `false` will show all rows. */
  @Prop() paginate: boolean = true;
  /** The zero-based index of the page to display */
  @Prop({ mutable: true }) page: number = 0;
  @Prop({ mutable: true }) rowsPerPage: number = 10;
  /** The total number of unpaginated rows.  This is ignored for client-side pagination.
   * For server-side pagination, omitting this prop will remove the last-page button.
   */
  @Prop() totalRows: number;
  @Prop() rowsPerPageOptions: number[];
  /** Do not sort or paginate client-side. Use events to send server requests instead. */
  @Prop() serverPaginate: boolean = false;
  @Prop() showOperationsBar: boolean = false;
  @Prop() getRowActions: (row: Object) => ITableRowAction[];
  @Prop() getMultiRowActions: (rows: string[]) => ITableRowAction[];

  @State() checkedRowIds: string[] = [];

  @Element() element: HTMLMxTableElement;

  @Event() mxRowCheck: EventEmitter<string[]>;
  @Event() mxVisibleRowsChange: EventEmitter<Object[]>;

  @Listen('mxCheck')
  onMxCheck(e: CustomEvent) {
    const { rowId, checked } = e.detail;
    if (!checked && this.checkedRowIds.includes(rowId)) {
      this.checkedRowIds = this.checkedRowIds.filter(id => id !== rowId);
    } else if (checked && !this.checkedRowIds.includes(rowId)) {
      this.checkedRowIds = [...this.checkedRowIds, rowId];
    }
    this.mxRowCheck.emit(this.checkedRowIds);
  }

  @Watch('sortBy')
  @Watch('sortAscending')
  @Watch('page')
  @Watch('rowsPerPage')
  @Watch('rows')
  onVisibleRowsChange() {
    this.mxVisibleRowsChange.emit(this.visibleRows);
  }

  @Watch('page')
  onPageChange() {
    // Scroll back to the top of the table on page change (if necessary)
    if (this.element.getBoundingClientRect().top < 0) this.element.scrollIntoView();
  }

  @Watch('sortBy')
  @Watch('sortAscending')
  onSortChange() {
    this.page = 0;
  }

  @Method()
  async getCheckedRowIds(): Promise<string[]> {
    return this.checkedRowIds;
  }

  @Method()
  async setCheckedRowIds(checkedRowIds: string[] = []) {
    this.checkedRowIds = checkedRowIds;
  }

  @Method()
  async checkAll() {
    if (this.rowIdProperty) {
      this.checkedRowIds = this.rows.map(row => row[this.rowIdProperty].toString());
    } else {
      this.checkedRowIds = this.getTableRows().map(row => row.rowId);
    }
  }

  @Method()
  async checkNone() {
    this.checkedRowIds = [];
  }

  getTableRows(): HTMLMxTableRowElement[] {
    return Array.from(
      this.element.querySelectorAll('mx-table-row:not(.header-row, .pagination-row)') as NodeListOf<
        HTMLMxTableRowElement
      >,
    );
  }

  onCheckAllClick(e: InputEvent) {
    e.preventDefault();
    if (this.checkedRowIds.length === 0) {
      this.checkAll();
    } else {
      this.checkedRowIds = [];
    }
  }

  setRowsChecked() {
    this.getTableRows().forEach(row => (row.checked = this.checkedRowIds.includes(row.rowId)));
  }

  componentWillLoad() {
    this.hasSlot = !!this.element.children.length;
  }

  componentDidRender() {
    if (this.actionMenu && !this.actionMenu.anchorEl) {
      this.actionMenu.anchorEl = this.actionMenuButton;
    }
    this.setRowsChecked();
  }

  componentDidLoad() {
    // Emit paginated rows right away.
    this.onVisibleRowsChange();
  }

  get cols(): ITableColumn[] {
    // If `columns` prop is not provided, create a column for each row object property
    if (!this.columns.length && this.rows.length) {
      return Object.keys(this.rows[0]).map(property => ({ property, heading: capitalize(property), sortable: true }));
    }
    return this.columns.map(col => ({
      ...col,
      sortable: col.sortable === false ? false : true, // Default sortable to true if not specified
    }));
  }

  get visibleRows(): Object[] {
    if (this.serverPaginate || (!this.paginate && !this.sortBy)) return this.rows;
    const offset = this.page * this.rowsPerPage;
    let rows = this.rows.slice();
    if (this.sortBy) this.sortRows(rows);
    rows = rows.slice(offset, offset + this.rowsPerPage);
    return rows;
  }

  get allRowsChecked(): boolean {
    return this.rows.length === this.checkedRowIds.length;
  }

  get someRowsChecked(): boolean {
    return this.checkedRowIds.length > 0 && this.checkedRowIds.length < this.rows.length;
  }

  get multiRowActions(): ITableRowAction[] {
    if (!this.getMultiRowActions) return [];
    return this.getMultiRowActions(this.checkedRowIds);
  }

  get gridStyle(): any {
    const display = this.autoWidth ? 'inline-grid' : 'grid';
    let gridTemplateColumns = this.checkable ? 'min-content ' : '';
    const autoColumnCount = this.cols.length + (this.getRowActions ? 1 : 0);
    gridTemplateColumns += `repeat(${autoColumnCount}, minmax(0, 1fr))`;
    return { display, gridTemplateColumns };
  }

  sortRows(rows: Object[]) {
    const sortByColumn = this.cols.find(c => c.property === this.sortBy);
    if (!sortByColumn) return;
    let sortCompare = sortByColumn.sortCompare;
    if (!sortCompare) {
      sortCompare = (a, b) => {
        const valueA = this.getCellSortableValue(a, sortByColumn);
        const valueB = this.getCellSortableValue(b, sortByColumn);
        if (typeof valueA === 'number' && typeof valueB === 'number') return valueB - valueA;
        return (valueA as string).localeCompare(valueB as string);
      };
    }
    rows.sort(sortCompare);
    if (!this.sortAscending) rows.reverse();
  }

  getCellSortableValue(row: Object, col: ITableColumn): string | number {
    if (col.getValue) return col.getValue(row);
    const val = row[col.property];
    if (['date', 'dateTime'].includes(col.type) || isDateObject(val)) return new Date(val).getTime();
    if (col.type === 'boolean') return val ? 1 : 0;
    return val;
  }

  getCellValue(row: Object, col: ITableColumn, rowIndex: number) {
    if (col.getValue) return col.getValue(row, rowIndex);
    const val = row[col.property];
    if (col.type === 'date' || isDateObject(val)) return new Date(val).toLocaleDateString();
    if (col.type === 'dateTime' || isDateObject(val)) return new Date(val).toLocaleString();
    if (col.type === 'boolean') return val ? 'Yes' : ''; // TODO: verify
    return val;
  }

  getHeaderClass(col: ITableColumn, colIndex: number) {
    let str = 'flex items-center subtitle2 px-16 py-18 ' + this.getAlignClass(col);
    if (colIndex === 0 && this.showOperationsBar) str += ' col-span-2';
    if (col.sortable && col.property) str += ' group cursor-pointer';
    if (col.headerClass) str += col.headerClass;
    return str;
  }

  getHeaderArrowClass(col: ITableColumn) {
    let str = 'ml-12';
    if (col.property !== this.sortBy) str += ' opacity-0 group-hover:opacity-40 transform rotate-180';
    else if (this.sortAscending) str += ' transform rotate-180';
    return str;
  }

  getAlignClass(col: ITableColumn) {
    let alignment = col.align || (col.type === 'number' ? 'right' : 'left');
    return alignment === 'right' ? 'justify-end' : alignment === 'center' ? 'justify-center' : 'justify-start';
  }

  onHeaderClick(col: ITableColumn) {
    if (!col.sortable || !col.property) return;
    if (this.sortBy !== col.property) {
      this.sortBy = col.property;
      this.sortAscending = true;
    } else {
      if (this.sortAscending) this.sortAscending = false;
      else {
        this.sortBy = null;
        this.sortAscending = true;
      }
    }
  }

  onPaginationChange(e: { detail: PaginationChangeEventDetail }) {
    this.page = e.detail.page;
    this.rowsPerPage = e.detail.rowsPerPage;
  }

  render() {
    const checkAllCheckbox = (
      <mx-checkbox
        checked={this.allRowsChecked}
        class={this.showOperationsBar ? 'ml-24' : null}
        indeterminate={this.someRowsChecked}
        onClick={this.onCheckAllClick.bind(this)}
        label-name="Select all rows"
        hide-label
      />
    );

    let multiRowActionUI;
    if (this.checkable) {
      multiRowActionUI =
        this.multiRowActions.length === 1 ? (
          <mx-button
            btn-type="outlined"
            {...this.multiRowActions[0]}
            class={!this.checkedRowIds.length ? 'hidden' : null}
          >
            {this.multiRowActions[0].value}
          </mx-button>
        ) : (
          <span class={!this.checkedRowIds.length ? 'hidden' : null}>
            <mx-button ref={el => (this.actionMenuButton = el)} btn-type="text" dropdown>
              <span class="h-full flex items-center">
                <i class="ph-gear text-1"></i>
              </span>
            </mx-button>
            <mx-menu ref={el => (this.actionMenu = el)}>
              {this.multiRowActions.map(action => (
                <mx-menu-item {...action}>{action.value}</mx-menu-item>
              ))}
            </mx-menu>
          </span>
        );
    }

    return (
      <Host class={'mx-table block' + (this.hoverable ? ' hoverable' : '')}>
        <div style={this.gridStyle}>
          {/* Operations Bar */}
          {this.showOperationsBar && (
            <div class="col-span-full py-12 flex items-center justify-between">
              <div class="flex items-center space-x-16">
                {this.checkable && checkAllCheckbox}
                {multiRowActionUI}
              </div>
              <mx-search class="w-240" dense placeholder="Search"></mx-search>
            </div>
          )}

          {/* Header Row */}
          <mx-table-row class="header-row">
            {this.checkable && !this.showOperationsBar && checkAllCheckbox}
            {this.cols.map((col: ITableColumn, colIndex: number) => {
              return (
                <div
                  id={`column-header-${colIndex}`}
                  role="columnheader"
                  class={this.getHeaderClass(col, colIndex)}
                  onClick={this.onHeaderClick.bind(this, col)}
                >
                  <div class="inline-flex items-center whitespace-nowrap select-none">
                    <span innerHTML={col.heading}></span>
                    {col.sortable && col.property && (
                      <div class={this.getHeaderArrowClass(col)} data-testid="arrow" innerHTML={arrowSvg}></div>
                    )}
                  </div>
                </div>
              );
            })}
            {this.getRowActions && <div></div>}
          </mx-table-row>

          <slot></slot>
          {/* HACK: Stencil refuses to render this as default slot content. :( */}
          {!this.hasSlot &&
            this.visibleRows.map((row, rowIndex) => (
              // Generated Body Rows
              <mx-table-row
                row-id={this.rowIdProperty ? row[this.rowIdProperty] : null}
                actions={this.getRowActions ? this.getRowActions(row) : undefined}
              >
                {this.cols.map((col: ITableColumn, colIndex: number) => (
                  <mx-table-cell
                    aria-describedby={`column-header-${colIndex}`}
                    class={[this.getAlignClass(col), col.cellClass].join(' ')}
                    innerHTML={this.getCellValue(row, col, rowIndex)}
                  ></mx-table-cell>
                ))}
              </mx-table-row>
            ))}
          {this.paginate && (
            // Pagination Row
            <mx-table-row class="pagination-row">
              <mx-pagination
                page={this.page}
                rows-per-page={this.rowsPerPage}
                rows-per-page-options={this.rowsPerPageOptions}
                total-rows={this.serverPaginate ? this.totalRows : this.rows.length}
                class="col-span-full p-0"
                onMxChange={this.onPaginationChange.bind(this)}
              />
            </mx-table-row>
          )}
        </div>
      </Host>
    );
  }
}
