nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org/"
npmScopes:
  moxiworks:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"