/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MxInput {
        "assistiveText": string;
        "dense": boolean;
        "error": boolean;
        "isActive": boolean;
        "isFocused": boolean;
        "label": string;
        "labelClass": string;
        "leftIcon": string;
        "name": string;
        "outerContainerClass": string;
        "rightIcon": string;
        "type": string;
        "value": string;
    }
}
declare global {
    interface HTMLMxInputElement extends Components.MxInput, HTMLStencilElement {
    }
    var HTMLMxInputElement: {
        prototype: HTMLMxInputElement;
        new (): HTMLMxInputElement;
    };
    interface HTMLElementTagNameMap {
        "mx-input": HTMLMxInputElement;
    }
}
declare namespace LocalJSX {
    interface MxInput {
        "assistiveText"?: string;
        "dense"?: boolean;
        "error"?: boolean;
        "isActive"?: boolean;
        "isFocused"?: boolean;
        "label"?: string;
        "labelClass"?: string;
        "leftIcon"?: string;
        "name"?: string;
        "outerContainerClass"?: string;
        "rightIcon"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "mx-input": MxInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mx-input": LocalJSX.MxInput & JSXBase.HTMLAttributes<HTMLMxInputElement>;
        }
    }
}
