
import * as d from './components';

export const DIRECTIVES = [
  d.MxBadge,
  d.MxBanner,
  d.MxButton,
  d.MxChart,
  d.MxCheckbox,
  d.MxChip,
  d.MxChipGroup,
  d.MxCircularProgress,
  d.MxCode,
  d.MxConfirmInput,
  d.MxDatePicker,
  d.MxDialog,
  d.MxDropdownMenu,
  d.MxFab,
  d.MxIconButton,
  d.MxImageUpload,
  d.MxInput,
  d.MxLinearProgress,
  d.MxMenu,
  d.MxMenuItem,
  d.MxModal,
  d.MxPageHeader,
  d.MxPagination,
  d.MxRadio,
  d.MxSearch,
  d.MxSelect,
  d.MxSnackbar,
  d.MxSwitch,
  d.MxTab,
  d.MxTabContent,
  d.MxTable,
  d.MxTableCell,
  d.MxTableRow,
  d.MxTabs,
  d.MxTimePicker,
  d.MxToggleButton,
  d.MxToggleButtonGroup,
  d.MxTooltip
];
